Fix explicit instantiations with storage classes
Due to their use, these shouldn't be static.
As an example, fixes errors like the following:

art/runtime/entrypoints/entrypoint_utils.h:403:1: error: explicit instantiation cannot have a storage class
EXPLICIT_FIND_METHOD_FROM_CODE_TYPED_TEMPLATE_DECL(kStatic);
^
art/runtime/entrypoints/entrypoint_utils.h:400:5: note: expanded from macro
'EXPLICIT_FIND_METHOD_FROM_CODE_TYPED_TEMPLATE_DECL'
    EXPLICIT_FIND_METHOD_FROM_CODE_TEMPLATE_DECL(_type, false);   \
    ^
art/runtime/entrypoints/entrypoint_utils.h:395:29: note: expanded from macro 'EXPLICIT_FIND_METHOD_FROM_CODE_TEMPLATE_DECL'
  static mirror::ArtMethod* FindMethodFromCode<_type, _access_check>(uint32_t method_idx,         \
                            ^

Change-Id: I5600529eb1a8bc39f418b403c54d613a6089c820