ART: Change behavior for rethrowing init failures
Allow to store a Throwable instance or a throwable class. Handle
rethrow accordingly, adding a parameter to enforce wrapping in
a NoClassDefFoundError.

Fix run-test 008 to expect spec-compliant behavior.

Change-Id: I703c2c6eaf34ad0e3bc0f5a104d65f2ff1b212ca